[package]
name = "serde_rusqlite"
version = "0.30.1"
edition = "2018"
description = "Serialize/deserialize rusqlite rows"
keywords = ["serde", "sqlite", "rusqlite", "serialization", "deserialization"]
categories = ["database", "encoding", ]
authors = ["Pro <twisted.fall@gmail.com>"]
license = "LGPL-3.0"
documentation = "https://docs.rs/serde_rusqlite"
readme = "README.md"
repository = "https://github.com/twistedfall/serde_rusqlite"

[dependencies]
rusqlite = "0.28"
serde = "1.0"

[dev-dependencies]
serde_bytes = "0.11"
serde_derive = "1.0"
